remembrances & mausoleums
Roundtable-Hold/tracker pull request #60
Opened 2022-04-02 18:30 UTC by thomasgraham18

added and linked all remembrances as well as mausoleums. all rewards also checkbox linked

2022-04-02 18:48 UTC, azy2 requested changes

2022-04-02 18:48 UTC, azy2 commented on data/rememberances.yaml
> +      - [1, "<a href=\"https://eldenring.wiki.fextralife.com/Remembrance+of+the+Grafted\">Remembrance Of The Grafted</a>", "Weapon - Axe Of Godrick", "Weapon - Grafted Dragon", "20,000 Runes", "Defea
I think we want 2 checkboxes for each Remembrance. So people can track which choice they made. Use subheadings, something like this:
```
- "<a href=\"https://eldenring.wiki.fextralife.com/Remembrance+of+the+Grafted\">Remembrance Of The Grafted</a> (20,000 Runes)"
- [1, "Axe Of Godrick"]
- [2, "Grafted Dragon"]
```

2022-04-02 18:48 UTC, azy2 commented on data/rememberances.yaml
> +      - [1, "Weeping Peninsula", "In the western area past the Church of Pilgrimage."]
These look good but maybe turn it into a list instead of a table. Just describe the region in the sentence.

2022-04-05 05:30 UTC, thomasgraham18 commented on data/rememberances.yaml
> +      - [1, "Weeping Peninsula", "In the western area past the Church of Pilgrimage."]
Requested changes applied. Sorry for the wait.

2022-04-05 13:10 UTC, azy2 approved these changes
Looks great thank you

2022-04-05 13:10 UTC, merged