Update bosses.yaml
Roundtable-Hold/tracker pull request #72
Opened 2022-04-07 20:52 UTC by grandnoble

Finished roundtable, weeping and most of liurnia, as well as a few various others. Also fixed some formatting I realized was messed up when the 4th column got added in last update.

2022-04-07 21:02 UTC, azy2 requested changes

2022-04-07 21:02 UTC, azy2 commented on data/bosses.yaml
> +      - [27, "Rykard, Lord of Blasphemy", "Volcano Manor", "", "Main boss. Semi-required for story progression.",
And here

2022-04-07 21:30 UTC, grandnoble commented on data/bosses.yaml
> +      - [30, "Godrick the Grafted", "Stormveil Castle", "20,000 runes, Godrick's Great Rune, Remembrance of the Grafted", "Main boss. Semi-required for story progression.", ]
Fixed sequence.

2022-04-07 21:31 UTC, grandnoble commented on data/bosses.yaml
> +      - [38, "Rennala, Queen of the Full Moon", "Raya Lucaria Academy", "", "Main boss. Semi-required for story progression.", ]
Fixed sequence.

2022-04-08 01:03 UTC, azy2 approved these changes

2022-04-08 01:03 UTC, merged